import React, { useState, useMemo } from 'react';
import {
  Flag, ShieldCheck, Mail, Phone, Send, Download,
  FileText, ShieldAlert, X, CheckCircle, ChevronDown,
  Building2, Calendar, Hash, Shield
} from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { jsPDF } from 'jspdf';

const Reports: React.FC = () => {
  const rawScans = useAppStore(state => state.scans);
  const scans = Array.isArray(rawScans) ? rawScans : [];

  const [selectedScanId, setSelectedScanId] = useState('');
  const [recipientOrg, setRecipientOrg] = useState('');
  const [message, setMessage] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [userProfile, setUserProfile] = useState({ name: 'Registered User', email: 'user@empowernet.ai' });

  React.useEffect(() => {
    const profile = localStorage.getItem('user_profile');
    if (profile) setUserProfile(JSON.parse(profile));
  }, []);

  const authorities = [
    { name: 'National Cyber Crime Reporting Portal (cybercrime.gov.in)', email: 'complaint@cybercrime.gov.in' },
    { name: 'Delhi Cyber Cell (cybercell.delhi@gov.in)', email: 'cybercell.delhi@gov.in' },
    { name: 'Mumbai Cyber Crime (cybercell.mumbai@mahapolice.gov.in)', email: 'cybercell.mumbai@mahapolice.gov.in' },
    { name: 'Bangalore Cyber Crime (cybercrime.blr@ksp.gov.in)', email: 'cybercrime.blr@ksp.gov.in' },
    { name: 'CERT-In (incident@cert-in.org.in)', email: 'incident@cert-in.org.in' }
  ];

  const selectedScan = useMemo(() => {
    return scans.find(s => s.id === selectedScanId);
  }, [scans, selectedScanId]);

  const generatePDF = () => {
    if (!selectedScan) return;

    const doc = new jsPDF();
    const timestamp = selectedScan.date || new Date().toLocaleString();

    // EmpowerNet logo text at top
    doc.setTextColor(139, 92, 246); // Violet-600
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('EMPOWERNET AI', 20, 25);
    doc.setFontSize(10);
    doc.text('FORENSIC LABORATORY DIVISION', 20, 32);

    // Header
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(14);
    doc.text('COMPLAINT UNDER SECTION 66 OF IT ACT 2000 / BNS 2023', 105, 50, { align: 'center' });
    
    // To Section
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('To,', 20, 65);
    doc.setFont('helvetica', 'normal');
    const auth = authorities.find(a => a.name === recipientOrg);
    doc.text(auth ? auth.name.split(' (')[0] : recipientOrg, 20, 72);

    // Complainant section
    doc.setFont('helvetica', 'bold');
    doc.text('1. Complainant Details', 20, 85);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: Registered User`, 20, 92);
    doc.text(`Platform: EmpowerNet AI Security System`, 20, 99);

    // Incident details section
    doc.setFont('helvetica', 'bold');
    doc.text('2. Incident Details', 20, 112);
    doc.setFont('helvetica', 'normal');
    doc.text(`Evidence Type: ${selectedScan.type.toUpperCase()}`, 20, 119);
    doc.text(`Timestamp: ${timestamp}`, 20, 126);
    
    const labelLines = doc.splitTextToSize(`Content Description: ${selectedScan.label}`, 170);
    doc.text(labelLines, 20, 133);
    
    let nextY = 133 + (labelLines.length * 7);

    if (message) {
        const msgLines = doc.splitTextToSize(`Context: ${message}`, 170);
        doc.text(msgLines, 20, nextY);
        nextY += (msgLines.length * 7);
    }
    nextY += 5;

    // Technical evidence section
    doc.setFont('helvetica', 'bold');
    doc.text('3. Technical Evidence Section', 20, nextY);
    nextY += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`Deepfake Probability / Confidence: ${selectedScan.confidence}`, 20, nextY);
    nextY += 7;
    doc.text(`Detection Model Used: EmpowerNet Advanced Synthetic DNA Scanner`, 20, nextY);
    nextY += 7;
    doc.text(`Ledger Anchored: Polygon Amoy Testnet (EVM)`, 20, nextY);
    nextY += 7;
    
    const hashLines = doc.splitTextToSize(`Blockchain Hash (Evidence Match): ${selectedScan.hash || 'N/A'}`, 170);
    doc.setFont('courier', 'normal');
    doc.text(hashLines, 20, nextY);
    nextY += (hashLines.length * 7);
    
    doc.setFont('helvetica', 'normal');
    const txLines = doc.splitTextToSize(`Transaction Hash: ${selectedScan.blockchainTx || 'N/A'}`, 170);
    doc.setFont('courier', 'normal');
    doc.text(txLines, 20, nextY);
    nextY += (txLines.length * 7) + 5;

    // Declaration
    doc.setFont('helvetica', 'bold');
    doc.text('4. Declaration', 20, nextY);
    nextY += 7;
    doc.setFont('helvetica', 'italic');
    doc.text('"I hereby declare that the information given above is true and correct', 20, nextY);
    nextY += 7;
    doc.text('to the best of my knowledge."', 20, nextY);

    // Footer
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by EmpowerNet AI Forensics Platform | Evidence Hash: ${selectedScan.hash || 'N/A'}`, 105, 280, { align: 'center' });

    doc.save(`CyberCrime_Complaint_${selectedScan.id}.pdf`);
  };

  const handleEmailReport = () => {
    if (!selectedScan || !recipientOrg) return;
    const auth = authorities.find(a => a.name === recipientOrg);
    if (!auth || !auth.email) return;

    const subject = `Cyber Crime Complaint - ${selectedScan.type.toUpperCase()} - ${selectedScan.date}`;
    const body = `Respected Sir/Madam,

I am writing to formally report an incident of ${selectedScan.type} encountered on ${selectedScan.date}.

Evidence Details:
- Evidence Type: ${selectedScan.type.toUpperCase()}
- Content Description: ${selectedScan.label}
- Confidence Score: ${selectedScan.confidence}
- Blockchain Proof Hash: ${selectedScan.hash || 'N/A'}
- Additional Context: ${message || 'None provided'}

I have attached the auto-generated EmpowerNet Forensic Report (PDF) to this email. Please review the cryptographic evidence for further investigation.

I hereby declare that the information given above is true and correct to the best of my knowledge.

Regards,
[Your Name]`;

    window.location.href = `mailto:${auth.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!recipientOrg || !selectedScanId) return;

    setIsSubmitting(true);
    await new Promise(resolve => setTimeout(resolve, 1500));
    setIsSubmitting(false);
    setSuccess(true);
  };

  return (
    <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-8 pb-20">

      {/* FORM SIDE */}
      <div className="space-y-6">
        <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-100 dark:border-gray-700 shadow-sm flex items-center gap-6 transition-colors">
          <div className="w-12 h-12 bg-violet-600 rounded-xl flex items-center justify-center text-white">
            <Flag size={24} />
          </div>
          <div>
            <h1 className="text-2xl font-bold dark:text-white transition-colors">Official Reporting</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">Submit verified evidence to authorities</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-800 p-8 rounded-2xl border border-gray-100 dark:border-gray-700 shadow-sm space-y-6 transition-colors">
          <div>
            <label className="text-xs font-black text-gray-400 dark:text-gray-500 uppercase mb-2 block tracking-wider">
              Select Forensic Record
            </label>
            <div className="relative">
              <select
                required
                value={selectedScanId}
                onChange={e => setSelectedScanId(e.target.value)}
                className="w-full p-4 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 rounded-xl appearance-none font-medium text-gray-700 dark:text-gray-200"
              >
                <option value="">-- Choose verified scan --</option>
                {scans.map(s => (
                  <option key={s.id} value={s.id}>
                    [{s.type.toUpperCase()}] {s.label.slice(0, 30)}... ({s.date.split(',')[0]})
                  </option>
                ))}
              </select>
              <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
            </div>
          </div>

          <div>
            <label className="text-xs font-black text-gray-400 dark:text-gray-500 uppercase mb-2 block tracking-wider">
              Reporting To Agency
            </label>
            <div className="relative">
              <select
                required
                value={recipientOrg}
                onChange={e => setRecipientOrg(e.target.value)}
                className="w-full p-4 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 rounded-xl appearance-none font-medium text-gray-700 dark:text-gray-200"
              >
                <option value="">-- Select Authority --</option>
                {authorities.map(org => (
                  <option key={org.name} value={org.name}>{org.name}</option>
                ))}
              </select>
              <Building2 className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" size={18} />
            </div>
          </div>

          <div>
            <label className="text-xs font-black text-gray-400 dark:text-gray-500 uppercase mb-2 block tracking-wider">
              Evidence Context
            </label>
            <textarea
              value={message}
              onChange={e => setMessage(e.target.value)}
              placeholder="Describe why this content is being reported (e.g., received via SMS from +91...)"
              className="w-full h-32 p-4 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 rounded-xl resize-none focus:ring-2 focus:ring-violet-500 outline-none transition-all dark:text-gray-200"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <button
              type="button"
              onClick={generatePDF}
              disabled={!selectedScanId}
              className="flex items-center justify-center gap-2 py-3 border-2 border-gray-100 dark:border-gray-700 rounded-xl font-bold text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 transition-colors"
            >
              <Download size={20} /> Download PDF
            </button>
            <button
              type="button"
              onClick={handleEmailReport}
              disabled={!selectedScanId || !recipientOrg}
              className="flex items-center justify-center gap-2 py-3 border-2 border-violet-100 dark:border-violet-900/30 text-violet-600 dark:text-violet-400 rounded-xl font-bold hover:bg-violet-50 dark:hover:bg-violet-900/20 disabled:opacity-50 transition-colors"
            >
              <Mail size={20} /> Send Report via Email
            </button>
          </div>

          <div className="pt-2">
            <button
              type="button"
              onClick={() => {
                if (selectedScanId) {
                  generatePDF();
                  setTimeout(() => {
                    window.open('https://cybercrime.gov.in/Webform/accept.aspx', '_blank');
                  }, 500);
                }
              }}
              disabled={!selectedScanId}
              title="Your PDF report will be downloaded. Attach it to the form that opens."
              className="w-full flex items-center justify-center gap-2 py-4 bg-violet-600 text-white rounded-xl font-bold shadow-lg shadow-violet-100 dark:shadow-none hover:bg-violet-700 active:scale-95 transition-all disabled:opacity-50"
            >
              <Shield size={20} /> Submit to cybercrime.gov.in
            </button>
          </div>
        </form>
      </div>

      {/* PREVIEW SIDE */}
      <div className="bg-gray-100 rounded-3xl p-1 border-4 border-white shadow-inner min-h-[600px] flex flex-col">
        <div className="bg-white rounded-[22px] flex-1 shadow-sm overflow-auto p-10 font-serif">
          {selectedScan ? (
            <div className="space-y-8 animate-in fade-in duration-500">
              <div className="flex justify-between items-start border-b-2 border-gray-900 pb-6">
                <div>
                  <h2 className="text-xl font-black text-violet-600 mb-1">EMPOWERNET AI</h2>
                  <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400">Forensic Laboratory Division</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] font-bold text-gray-400 mb-1 leading-none uppercase">Forensic Case ID</p>
                  <p className="font-mono text-xs font-bold text-gray-900">EV-2025-{selectedScan.id.slice(-8).toUpperCase()}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-8 text-[11px] border-b border-gray-100 pb-6">
                <div className="space-y-4">
                  <div>
                    <p className="font-bold uppercase text-gray-400 mb-1 tracking-widest">Complainant Details</p>
                    <p className="font-bold text-gray-900 text-sm">{userProfile.name}</p>
                    <p className="text-gray-500">{userProfile.email}</p>
                  </div>
                  <div>
                    <p className="font-bold uppercase text-gray-400 mb-1 tracking-widest">Reporting To</p>
                    <p className="font-bold text-violet-600">{recipientOrg || 'Selection Pending'}</p>
                  </div>
                </div>
                <div className="space-y-4">
                  <div>
                    <p className="font-bold uppercase text-gray-400 mb-1 tracking-widest">Incident Timestamp</p>
                    <p className="font-bold text-gray-900">{selectedScan.date || new Date().toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="font-bold uppercase text-gray-400 mb-1 tracking-widest">Verification Status</p>
                    <div className="flex items-center gap-2">
                       <ShieldCheck size={14} className="text-green-600" />
                       <span className="font-black text-green-600 uppercase">Cryptographically Secured</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <div className="flex justify-between items-center bg-gray-900 text-white p-4 rounded-xl">
                   <div>
                     <p className="text-[9px] font-bold opacity-60 uppercase tracking-widest">Detected Incident Type</p>
                     <p className="text-lg font-black">{selectedScan.type.toUpperCase()}</p>
                   </div>
                   <div className="text-right">
                     <p className="text-[9px] font-bold opacity-60 uppercase tracking-widest">AI Confidence</p>
                     <p className="text-xl font-black text-violet-400">{selectedScan.confidence}</p>
                   </div>
                </div>
                
                <div className="p-4 bg-violet-50 rounded-xl border border-violet-100">
                   <p className="text-[9px] font-black text-violet-800 uppercase tracking-widest mb-1">Evidence Source / Label</p>
                   <p className="text-xs font-bold text-gray-800 line-clamp-2">{selectedScan.label}</p>
                </div>
              </div>

              <div className="p-6 bg-gray-50 rounded-xl border border-dashed border-gray-200 space-y-4">
                <div>
                  <p className="font-bold uppercase text-gray-400 text-[9px] mb-2 tracking-widest">Forensic Metadata</p>
                  <p className="text-xs font-medium text-gray-600">Risk Confidence: <span className="text-gray-900 font-bold">{selectedScan.confidence}</span></p>
                </div>

                {selectedScan.explanation && selectedScan.explanation.length > 0 && (
                  <div>
                    <p className="font-bold uppercase text-gray-400 text-[9px] mb-2 tracking-widest">Analysis Triggers</p>
                    <div className="space-y-1">
                      {selectedScan.explanation.slice(0, 2).map((exp, i) => (
                        <p key={i} className="text-[10px] text-gray-600 leading-tight">• {exp}</p>
                      ))}
                    </div>
                  </div>
                )}

                <div>
                  <p className="font-bold uppercase text-gray-400 text-[9px] mb-2 tracking-widest">Blockchain Proof</p>
                  <div className="space-y-2">
                    <div className="flex flex-col gap-1">
                      <span className="text-[8px] font-bold text-gray-400">SHA-256 HASH</span>
                      <p className="font-mono text-[9px] text-gray-500 break-all">{selectedScan.hash}</p>
                    </div>
                    <div className="flex flex-col gap-1 p-3 bg-violet-50 rounded-lg border border-violet-100">
                      <p className="text-[8px] font-black text-violet-600 uppercase tracking-widest">Polygon Transaction</p>
                      <p className="text-[9px] font-mono text-violet-500 break-all">{selectedScan.blockchainTx || 'Tx Hash Pending...'}</p>
                    </div>
                  </div>
                </div>
              </div>

              <div>
                <p className="font-bold uppercase text-gray-400 text-[9px] mb-2 tracking-widest">Verification Statement</p>
                <p className="text-[10px] text-violet-600 leading-relaxed font-bold italic border-l-2 border-violet-600 pl-4 py-1">
                  "This report is cryptographically verifiable and anchored on the Polygon blockchain. Any modification invalidates this proof."
                </p>
              </div>

              <div className="pt-20 text-center opacity-30 grayscale pointer-events-none select-none">
                <ShieldCheck size={64} className="mx-auto text-violet-600 mb-4" />
                <p className="text-[10px] font-black uppercase tracking-[0.3em]">SECURE FORENSIC PROOF</p>
              </div>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-center p-10 opacity-30">
              <FileText size={48} className="mb-4 text-violet-600" />
              <p className="text-lg font-bold text-gray-900 mb-2">Report Preview Missing</p>
              <p className="text-sm">Select a scan record from the form to generate a live forensic dossier preview.</p>
            </div>
          )}
        </div>
      </div>

      {/* SUCCESS MODAL */}
      {success && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-6">
          <div className="bg-white rounded-3xl p-10 max-w-sm w-full text-center shadow-2xl animate-in zoom-in duration-300">
            <div className="w-20 h-20 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <CheckCircle size={40} />
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-2">Report Submitted</h3>
            <p className="text-gray-500 mb-8 leading-relaxed">
              Forensic dossier has been successfully transmitted to <b>{recipientOrg}</b>. Reference ID: {Date.now().toString().slice(-6)}
            </p>
            <button
              onClick={() => {
                setSuccess(false);
                setSelectedScanId('');
                setRecipientOrg('');
                setMessage('');
              }}
              className="w-full py-4 bg-gray-900 text-white rounded-xl font-bold hover:bg-gray-800 transition-colors"
            >
              Close Window
            </button>
          </div>
        </div>
      )}

    </div>
  );
};

export default Reports;
